spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DATABASE:sgblug_dev}
    username: ${PG_USER:sgblug}
    password: ${PG_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
